# Generated by Django 3.0.4 on 2020-03-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
