# Generated by Django 3.0.4 on 2020-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='booksale',
            new_name='signup',
        ),
    ]
